[project]
name = "wan-gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "httpx",
    "uvicorn>=0.38.0",
    "pydantic",
]
